# -*- python -*-

Import('env')
import sys
wxenv = env.Clone()

files = [
	]


if wxenv['HAVE_WX']:
	files += [
		'mcmMain.cpp',
		'GUI/MCMdebug.cpp',
		'GUI/MemcardManager.cpp',
		'GUI/MemcardSelectPanel.cpp',
		'MemoryCards/GCMemcard.cpp',
		]


exeGUI = env['binary_dir'] + 'MemcardManager'

wxenv.Program(exeGUI, files)
