# -*- python -*-

Import('env')
import sys
wxenv = env.Clone()

files = [
	]

libs = [
	'common',
	]

if wxenv['HAVE_WX']:
	files += [
		'mcmMain.cpp',
		'GUI/MCMdebug.cpp',
		'GUI/MemcardManager.cpp',
		'MemoryCards/GCMemcard.cpp',
		]

LIBS = libs

wxenv.Append(
	LIBS = libs
	)

exeGUI = env['binary_dir'] + 'MemcardManager'

wxenv.Program(exeGUI, files)
