# -*- python -*-

Import('env')
import sys
wxenv = env.Clone()

files = [
	]

libs = [
	'common',
	]

if wxenv['HAVE_WX']:
	files += [
		'Src/mcmMain.cpp',
		'Src/GUI/MCMdebug.cpp',
		'Src/GUI/MemcardManager.cpp',
		'Src/MemoryCards/GCMemcard.cpp',
		]

LIBS = libs

wxenv.Append(
	LIBS = libs
	)

exeGUI = env['binary_dir'] + 'MemcardManager'

wxenv.Program(exeGUI, files)
